### ISSUE TITLE
Carthage error: GitHub API request failed: DoesNotExist

### ISSUE THREAD

**Issue by FlorianCP** [MattCheetham/HarvestKit-Swift#89]
Hey Matt,

I'm new to Carthage and tried to use your HarvestKit. However, when running "carthage bootstrap", Carthage gives me the mentioned error:

> GitHub API request failed: DoesNotExist

Not sure if this is an issue of Carthage, Me or your project.
I haven't got any other projects included in my Cartfile, also running "carthage bootstrap --verbose" does not give me any extra info.

Any help would be greatly appreciated!

**Comment by MattCheetham** [comment]
Hey @FlorianCP,

I've never seen that one before. At first glance it sounds like Carthage can't find either this project or one of it's dependencies correctly. Are you able to post the contents of your Cartfile so I can try and replicate here?

Thanks.

**Comment by FlorianCP** [comment]
Sure, it's actually only your Github in there:

> github "MattCheetham/HarvestKit-Swift" ~> 1.2

That's why I'm so puzzled.
However, I did not use Carthage before, so I'm really not sure if it's my Carthage installation, the Cartfile or whatever else may be problematic.

**Comment by MattCheetham** [comment]
Just created a brand new project with that as the Cartfile and "carthage bootstrap --verbose" and it checked them out correctly. Looks like there is an issue with ThunderRequest (A dependency) not building correctly due to a tvOS setting bug which I will fix shortly but I'm definitely not getting the same error as you.

It might be worth asking over in the Carthage project about the error to see if they can shed some light on it for you.

Sorry I haven't been able to be more help on this.

**Comment by FlorianCP** [comment]
I'll make sure to reinstall Carthage and see if the issue persists. If it does, I'll ask in the Carthage project.

Thanks for helping out a Carthage newbie @MattCheetham!

**Comment by FlorianCP** [comment]
Hey @MattCheetham and others experiencing the issue - I solved it by uninstalling and reinstalling Carthage from Homebrew. Did not do anything different than last time while installing, but now it works.
Thanks again for your help @MattCheetham!

**Comment by MattCheetham** [comment]
Excellent. Glad to hear this is fixed for you.
